info:
  version: 1.0.0
  description: WebUI Configuration
  http-version: 2

configuration:
  # 5G mode
  spec-compliant-sdf: false
  enableAuthentication: false
  send-pebble-notifications: false
  cfgport: 5000

  # MongoDB configuration
  mongodb:
    name: aether
    url: "mongodb://172.28.31.5:27017/?replicaSet=rs0&connectTimeoutMS=10000"
    authKeysDbName: authentication
    authUrl: "mongodb://172.28.31.5:27017/?replicaSet=rs0&connectTimeoutMS=10000"
    webuiDbName: aether
    webuiDbUrl: "mongodb://172.28.31.5:27017/?replicaSet=rs0&connectTimeoutMS=10000"
    checkReplica: false

  # ROC endpoint configuration
  managedByConfigPod:
    syncUrl: http://roc-service:8080/sync
    enabled: false

  # SSM (Secure Storage Module) configuration
  ssm:
    ssm-uri: https://localhost:9000
    allow-ssm: true
    tls-insecure: true
    ssm-synchronize:
      enable: true
      interval-minute: 30
      max-keys-create: 5
      delete-missing: true
      max-sync-keys: 5
      max-sync-users: 5
      max-sync-rotations: 5
    login: # SSM login credentials not to be used in production, in production use environment variables or secret management systems
      service-id: webconsole
      password: 3334464250706421444c234e43256321
    m-tls:
      crt: client-webconsole.crt
      key: client-webconsole.key
      ca: ca.crt
    # read in cascade if gcm is false then cbc is used if gcm is true cbc is ignored, both is false no encryption is used (disabled SSM jjjj)
    is-encrypt-aes-gcm: true
    is-encrypt-aes-cbc: false
  vault:
    vault-uri: "https://vault.example.com:8200"
    allow-vault: true
    tls-insecure: false
    
    # Método 1: mTLS (recomendado para producción)
    cert-role: "webconsole-cert-role"
    m-tls:
      crt: "/path/to/client.crt"
      key: "/path/to/client.key"
      ca: "/path/to/ca.crt"
    
    # Método 2: Kubernetes
    k8s-role: "webconsole-role"
    k8s-jwt-path: "/var/run/secrets/kubernetes.io/serviceaccount/token"
    
    # Método 3: AppRole
    role-id: "${VAULT_ROLE_ID}"
    secret-id: "${VAULT_SECRET_ID}"

    key-kv-path: "secret/data/k4keys"
    key-kv-metadata-path: "secret/metadata/k4keys"
    transit-keys-list-path: "transit/keys"
    transit-key-create-fmt: "transit/keys/%s"
    transit-key-rotate-fmt: "transit/keys/%s/rotate"

logger:
  WEBUI:
    debugLevel: debug