info:
  version: 1.0.0
  description: WebUI Configuration
  http-version: 2

configuration:
  # 5G mode
  spec-compliant-sdf: false
  enableAuthentication: false
  send-pebble-notifications: false
  cfgport: 5000

  # MongoDB configuration
  mongodb:
    name: aether
    url: "mongodb://172.28.31.5:27017/?replicaSet=rs0&connectTimeoutMS=10000"
    authKeysDbName: authentication
    authUrl: "mongodb://172.28.31.5:27017/?replicaSet=rs0&connectTimeoutMS=10000"
    webuiDbName: aether
    webuiDbUrl: "mongodb://172.28.31.5:27017/?replicaSet=rs0&connectTimeoutMS=10000"
    checkReplica: false

  # ROC endpoint configuration
  managedByConfigPod:
    syncUrl: http://roc-service:8080/sync
    enabled: false

  # SSM (Secure Storage Module) configuration
  ssm:
    ssm-uri: https://localhost:9000
    allow-ssm: false
    tls-insecure: true
    ssm-synchronize:
      enable: false
      interval-minute: 30
      max-keys-create: 5
      delete-missing: true
      max-sync-keys: 5
      max-sync-users: 5
      max-sync-rotations: 5
    login: # SSM login credentials not to be used in production, in production use environment variables or secret management systems
      service-id: webconsole
      password: 3334464250706421444c234e43256321
    m-tls:
      crt: client-webconsole.crt
      key: client-webconsole.key
      ca: ca.crt
    # read in cascade if gcm is false then cbc is used if gcm is true cbc is ignored, both is false no encryption is used (disabled SSM jjjj)
    is-encrypt-aes-gcm: true
    is-encrypt-aes-cbc: false
  vault:
    vault-uri: "http://127.0.0.1:8200"
    allow-vault: true
    tls-insecure: true
    
    # AppRole authentication
    role-id: "${VAULT_ROLE_ID}"
    secret-id: "${VAULT_SECRET_ID}"
    
    # Custom mount paths for auth methods (optional, uses defaults if not specified)
    approle-mount-path: "auth-dev-approle"  # Default: "approle"
    # k8s-mount-path: "kubernetes"   # Default: "kubernetes"
    cert-mount-path: "auth-dev-cert"        # Default: "cert"

    key-kv-path: "kv-dev/data/k4keys"
    key-kv-metadata-path: "kv-dev/metadata/k4keys"
    transit-keys-list-path: "transit-dev/keys"
    transit-key-create-fmt: "transit-dev/keys/%s"
    transit-key-rotate-fmt: "transit-dev/keys/%s/rotate"
    transit-key-rewrap-fmt: "transit-dev/rewrap/%s"
    transit-keys-encrypt-path: "transit-dev/encrypt"

    ssm-synchronize:
      enable: true
      interval-minute: 30
      max-keys-create: 5
      delete-missing: true
      max-sync-keys: 5
      max-sync-users: 5
      max-sync-rotations: 5

logger:
  WEBUI:
    debugLevel: debug
  